=== tianyl1984/myWebApp/src/main/java/com/hzth/myapp/xml/person.dtd
<!ELEMENT person(name,sex,height,birthday,phone,address?)>
<!ELEMENT name(xname,cname?)>
<!ELEMENT xname(#PCDATA)>
<!ELEMENT cname(#PCDATA)>
<!ELEMENT sex(male|famale)>
<!ELEMENT height(PCDATA)>
<!ELEMENT birthday(PCDATA)>
<!ELEMENT phone(PCDATA)>
<!ELEMENT address(PCDATA)>
<!ATTLIST height dw (cm|m) #REQUIRED>

=== tianyl1984/myWebApp/src/main/java/com/hzth/myapp/xml/testA.xml
<?xml version="1.0" encoding="GB2312"?>
<!DOCTYPE person SYSTEM "person.dtd">
<person>
	<name>
		<xname>zhangsan</xname>
		<cname>zhangsi</cname>
	</name>
	<sex>
	male
	</sex>
	<height dw="cm">
	178
	</height>
	<birthday>
	1985-10-10
	</birthday>
	<phone>
	123456789
	</phone>
	<address>
	beijing
	</address>
</person>
